on:
  push:
    branches: [ main ]
name: Deploy Qc Domain hat
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.server }}
        port: ${{ secrets.port }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password
        server-dir: ./hat/
